name: leashedmobsteleport
version: '1.5.1'
main: com.comonier.leashedmobsteleport.LeashedMobsTeleport
api-version: '1.21'
author: comonier
description: Teleport leashed mobs across dimensions and allow leashing any mob.
softdepend: [zzzzzz_last]

commands:
  lmt:
    description: Comandos principais do plugin (Reload e Toggle).
    usage: /lmt [reload]

permissions:
  leashedmobsteleport.use:
    description: Allows players to leash mobs and teleport them.
    default: true
  leashedmobsteleport.admin:
    description: Allows reloading the plugin configuration.
    default: op
