name: leashedmobsteleport
version: '1.2'
main: com.comonier.leashedmobsteleport.LeashedMobsTeleport
api-version: '1.21'
author: comonier
description: Teleport leashed mobs across dimensions and allow leashing any mob.

permissions:
  leashedmobsteleport.use:
    description: Allows players to leash mobs and teleport them.
    default: true
